const { initializeApp } = require('firebase/app');
const { getFirestore, collection, setDoc, doc } = require('firebase/firestore');
const { getAuth, signInWithEmailAndPassword, createUserWithEmailAndPassword } = require('firebase/auth');

const firebaseConfig = {
  apiKey: "AIzaSyAEOEPEdbUgz4BwJIk5mX7D4US5Agm6avE",
  authDomain: "fetchmeup-727fe.firebaseapp.com",
  projectId: "fetchmeup-727fe",
  storageBucket: "fetchmeup-727fe.firebasestorage.app",
  messagingSenderId: "549661622643",
  appId: "1:549661622643:web:617fdae14421fa6c93c506",
  measurementId: "G-99KJJCFG4G"
};

const app = initializeApp(firebaseConfig);
const db = getFirestore(app);
const auth = getAuth(app);

const MERCHANTS = [
  {
    id: 'r1',
    name: "Lachi's Sans Rival",
    category: 'Restaurant',
    address: 'J.C. Aquino Ave, Butuan City',
    barangay: 'Libertad',
    image: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=400&h=300&fit=crop',
    rating: 4.8,
    isOpen: true,
    openHours: '8:00 AM - 9:00 PM',
    description: 'Famous for their Sans Rival cake and Filipino-fusion dishes. A Butuan institution.',
    tags: ['Cakes', 'Filipino', 'Desserts', 'Fine Dining'],
    isFeatured: true,
    isVerified: true,
  },
  {
    id: 'r2',
    name: 'Jollibee - Butuan Langihan',
    category: 'Restaurant',
    address: 'A.D. Curato St, Butuan City',
    barangay: 'Doongan',
    image: 'https://images.unsplash.com/photo-1626082896492-766af4eb6501?w=500',
    rating: 4.5,
    isOpen: true,
    openHours: '7:00 AM - 11:00 PM',
    description: "The country's #1 fast food chain. Chickenjoy, Yumburger, and Jolly Spaghetti.",
    tags: ['Fast Food', 'Chicken', 'Burgers', 'Filipino'],
    isVerified: true,
  },
  {
    id: 'r3',
    name: 'Kusina sa Butuan',
    category: 'Restaurant',
    address: 'Montilla Blvd, Butuan City',
    barangay: 'Obrero',
    image: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=400&h=300&fit=crop',
    rating: 4.6,
    isOpen: true,
    openHours: '10:00 AM - 9:00 PM',
    description: 'Authentic Butuanon cuisine with local flavors and traditional recipes.',
    tags: ['Filipino', 'Local', 'Carinderia', 'Budget Meals'],
    isFeatured: true,
    isVerified: false,
  },
  {
    id: 'r4',
    name: 'Chowking - Robinsons Butuan',
    category: 'Restaurant',
    address: 'Robinsons Place, Butuan City',
    barangay: 'Limaha',
    image: 'https://images.unsplash.com/photo-1585032226651-759b368d7246?w=500',
    rating: 4.3,
    isOpen: true,
    openHours: '10:00 AM - 9:00 PM',
    description: 'Chinese-Filipino fast food favorites. Chao Fan, Lauriat, and Halo-Halo.',
    tags: ['Chinese', 'Fast Food', 'Asian', 'Rice Meals'],
    isVerified: true,
  },
  {
    id: 'r5',
    name: 'Mang Inasal - Butuan',
    category: 'Restaurant',
    address: 'J.C. Aquino Ave, Butuan City',
    barangay: 'Libertad',
    image: 'https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?w=500',
    rating: 4.4,
    isOpen: true,
    openHours: '9:00 AM - 10:00 PM',
    description: 'Filipino inasal chicken masters. Unli-rice with every meal!',
    tags: ['Filipino', 'Chicken', 'Grilled', 'Budget Meals'],
    isVerified: true,
  },
  {
    id: 'r6',
    name: "Penong's BBQ",
    category: 'Restaurant',
    address: 'Montilla Blvd, Butuan City',
    barangay: 'Baan KM 3',
    image: 'https://images.unsplash.com/photo-1532636875-6faeb12148c4?w=500',
    rating: 4.7,
    isOpen: true,
    openHours: '10:00 AM - 10:00 PM',
    description: 'Best BBQ and grilled dishes in Butuan. Famous for chicken and pork BBQ.',
    tags: ['BBQ', 'Grilled', 'Filipino', 'Chicken'],
    isFeatured: true,
    isVerified: true,
  },
  {
    id: 'g1',
    name: 'Gaisano Mall Grocery',
    category: 'Grocery',
    address: 'J.C. Aquino Ave, Butuan City',
    barangay: 'Libertad',
    image: 'https://images.unsplash.com/photo-1604719312566-8912e9227c6a?w=400&h=300&fit=crop',
    rating: 4.4,
    isOpen: true,
    openHours: '9:00 AM - 8:00 PM',
    description: 'Full-service grocery with fresh produce, meats, and household essentials.',
    tags: ['Grocery', 'Fresh Produce', 'Household', 'Snacks'],
    isVerified: true,
  },
  {
    id: 'g2',
    name: 'Robinsons Supermarket',
    category: 'Grocery',
    address: 'Robinsons Place, Butuan City',
    barangay: 'Limaha',
    image: 'https://images.unsplash.com/photo-1578916171728-46686eac8d58?w=400&h=300&fit=crop',
    rating: 4.5,
    isOpen: true,
    openHours: '10:00 AM - 9:00 PM',
    description: 'Premium supermarket with imported and local goods.',
    tags: ['Supermarket', 'Imported', 'Fresh', 'Premium'],
    isVerified: true,
  },
  {
    id: 'g3',
    name: 'SaveMore Market - Butuan',
    category: 'Grocery',
    address: 'A.D. Curato St, Butuan City',
    barangay: 'Doongan',
    image: 'https://images.unsplash.com/photo-1542838132-92c53300491e?w=400&h=300&fit=crop',
    rating: 4.3,
    isOpen: true,
    openHours: '8:00 AM - 9:00 PM',
    description: 'Everyday low prices on groceries and daily needs.',
    tags: ['Grocery', 'Budget', 'Daily Needs', 'Wholesale'],
    isVerified: false,
  },
  {
    id: 'p1',
    name: 'Mercury Drug - Butuan',
    category: 'Pharmacy',
    address: 'J.C. Aquino Ave, Butuan City',
    barangay: 'Obrero',
    image: 'https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=400&h=300&fit=crop',
    rating: 4.6,
    isOpen: true,
    openHours: '7:00 AM - 10:00 PM',
    description: "The Philippines' leading drugstore. Medicines, vitamins, and personal care.",
    tags: ['Medicine', 'Vitamins', 'Personal Care', 'Health'],
    isVerified: true,
  },
  {
    id: 'p2',
    name: 'Rose Pharmacy - Langihan',
    category: 'Pharmacy',
    address: 'Langihan Rd, Butuan City',
    barangay: 'Doongan',
    image: 'https://images.unsplash.com/photo-1576602976047-174e57a47881?w=400&h=300&fit=crop',
    rating: 4.4,
    isOpen: true,
    openHours: '8:00 AM - 9:00 PM',
    description: 'Wide selection of medicines and healthcare products at competitive prices.',
    tags: ['Medicine', 'Healthcare', 'Generics', 'Wellness'],
    isVerified: true,
  },
  {
    id: 'p3',
    name: 'Watsons - Robinsons Butuan',
    category: 'Pharmacy',
    address: 'Robinsons Place, Butuan City',
    barangay: 'Limaha',
    image: 'https://images.unsplash.com/photo-1631549916768-4119b2e5f926?w=400&h=300&fit=crop',
    rating: 4.5,
    isOpen: true,
    openHours: '10:00 AM - 9:00 PM',
    description: 'Health & beauty store with skincare, cosmetics, and pharmacy services.',
    tags: ['Beauty', 'Skincare', 'Medicine', 'Cosmetics'],
    isVerified: true,
  },
  {
    id: 'h1',
    name: 'Ace Hardware - Butuan',
    category: 'Hardware',
    address: 'Robinsons Place, Butuan City',
    barangay: 'Limaha',
    image: 'https://images.unsplash.com/photo-1504148455328-c376907d081c?w=400&h=300&fit=crop',
    rating: 4.3,
    isOpen: true,
    openHours: '10:00 AM - 8:00 PM',
    description: 'Tools, paint, plumbing, electrical supplies, and home improvement essentials.',
    tags: ['Tools', 'Paint', 'Plumbing', 'Electrical'],
    isVerified: true,
  },
  {
    id: 'h2',
    name: 'Citi Hardware - Butuan',
    category: 'Hardware',
    address: 'A.D. Curato St, Butuan City',
    barangay: 'Baan KM 3',
    image: 'https://images.unsplash.com/photo-1572981779307-38b8cabb2407?w=400&h=300&fit=crop',
    rating: 4.5,
    isOpen: true,
    openHours: '7:30 AM - 7:00 PM',
    description: "Mindanao's largest hardware chain. Building materials, tools, and more.",
    tags: ['Construction', 'Building Materials', 'Tools', 'Wholesale'],
    isFeatured: true,
    isVerified: true,
  },
  {
    id: 'e1',
    name: 'Silicon Valley - Gaisano',
    category: 'Electronics',
    address: 'Gaisano Mall, Butuan City',
    barangay: 'Libertad',
    image: 'https://images.unsplash.com/photo-1550009158-9ebf69173e03?w=400&h=300&fit=crop',
    rating: 4.2,
    isOpen: true,
    openHours: '10:00 AM - 8:00 PM',
    description: 'Gadgets, phones, laptops, and computer accessories.',
    tags: ['Phones', 'Laptops', 'Gadgets', 'Accessories'],
    isVerified: false,
  },
  {
    id: 'e2',
    name: 'Octagon Computer Superstore',
    category: 'Electronics',
    address: 'J.C. Aquino Ave, Butuan City',
    barangay: 'Obrero',
    image: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=400&h=300&fit=crop',
    rating: 4.4,
    isOpen: true,
    openHours: '9:00 AM - 7:00 PM',
    description: 'Computers, peripherals, networking, and tech accessories.',
    tags: ['Computers', 'PC Parts', 'Networking', 'Tech'],
    isVerified: true,
  },
  {
    id: 'b1',
    name: "Julie's Bakeshop - Butuan",
    category: 'Bakery',
    address: 'Montilla Blvd, Butuan City',
    barangay: 'Obrero',
    image: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=400&h=300&fit=crop',
    rating: 4.3,
    isOpen: true,
    openHours: '6:00 AM - 8:00 PM',
    description: 'Fresh bread, pastries, and cakes baked daily. A Filipino bakery tradition.',
    tags: ['Bread', 'Pastries', 'Cakes', 'Pandesal'],
    isVerified: true,
  },
  {
    id: 'b2',
    name: 'Goldilocks - Butuan',
    category: 'Bakery',
    address: 'J.C. Aquino Ave, Butuan City',
    barangay: 'Libertad',
    image: 'https://images.unsplash.com/photo-1535141192574-5d4897c82536?w=500',
    rating: 4.6,
    isOpen: true,
    openHours: '8:00 AM - 9:00 PM',
    description: 'Premium cakes, pastries, and celebration packages for every occasion.',
    tags: ['Cakes', 'Celebration', 'Pastries', 'Premium'],
    isVerified: true,
  },
  {
    id: 'c1',
    name: "Bo's Coffee - Butuan",
    category: 'Cafe',
    address: 'Robinsons Place, Butuan City',
    barangay: 'Limaha',
    image: 'https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?w=400&h=300&fit=crop',
    rating: 4.5,
    isOpen: true,
    openHours: '8:00 AM - 9:00 PM',
    description: 'Proudly Filipino coffee brand. Locally sourced beans, great atmosphere.',
    tags: ['Coffee', 'Espresso', 'Pastries', 'Local'],
    isFeatured: true,
    isVerified: true,
  },
  {
    id: 'c2',
    name: 'Cafe Caliente',
    category: 'Cafe',
    address: 'Guingona Park Area, Butuan City',
    barangay: 'Baan KM 3',
    image: 'https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=400&h=300&fit=crop',
    rating: 4.7,
    isOpen: true,
    openHours: '7:00 AM - 10:00 PM',
    description: 'Cozy cafe with specialty brews, milk teas, and light meals.',
    tags: ['Coffee', 'Milk Tea', 'Snacks', 'Cozy'],
    isVerified: false,
  },
  {
    id: 's1',
    name: "Aling Nena's Store",
    category: 'Sari-Sari',
    address: 'Purok 5, Ampayon, Butuan City',
    barangay: 'Ampayon',
    image: 'https://images.unsplash.com/photo-1556767576-5ec41e3239ea?w=400&h=300&fit=crop',
    rating: 4.1,
    isOpen: true,
    openHours: '6:00 AM - 9:00 PM',
    description: 'Your neighborhood sari-sari store. Snacks, drinks, and daily essentials.',
    tags: ['Snacks', 'Drinks', 'Essentials', 'Tingi'],
    isVerified: false,
  },
  {
    id: 'm1',
    name: 'Butuan City Public Market',
    category: 'Market',
    address: 'Montilla Blvd, Butuan City',
    barangay: 'Obrero',
    image: 'https://images.unsplash.com/photo-1488459716781-31db52582fe9?w=400&h=300&fit=crop',
    rating: 4.2,
    isOpen: true,
    openHours: '4:00 AM - 6:00 PM',
    description: "Fresh fish, meat, vegetables, and fruits. The heart of Butuan's food supply.",
    tags: ['Fresh Fish', 'Meat', 'Vegetables', 'Fruits'],
    isFeatured: true,
    isVerified: false,
  },
  {
    id: 'cl1',
    name: 'Penshoppe - Robinsons',
    category: 'Clothing',
    address: 'Robinsons Place, Butuan City',
    barangay: 'Limaha',
    image: 'https://images.unsplash.com/photo-1441984904996-e0b6ba687e04?w=400&h=300&fit=crop',
    rating: 4.4,
    isOpen: true,
    openHours: '10:00 AM - 9:00 PM',
    description: 'Trendy Filipino fashion brand with casual wear and accessories.',
    tags: ['Fashion', 'Casual', 'Trendy', 'Accessories'],
    isVerified: true,
  },
  {
    id: 'ps1',
    name: 'Pet City - Butuan',
    category: 'Pet Shop',
    address: 'J.C. Aquino Ave, Butuan City',
    barangay: 'Libertad',
    image: 'https://images.unsplash.com/photo-1583337130417-13104dec14a8?w=400&h=300&fit=crop',
    rating: 4.5,
    isOpen: true,
    openHours: '9:00 AM - 7:00 PM',
    description: 'Pet food, accessories, grooming supplies, and vet-recommended products.',
    tags: ['Pet Food', 'Dog', 'Cat', 'Grooming'],
    isVerified: true,
  },
];

async function seed() {
  console.log('🚀 Authenticating...');
  try {
    await signInWithEmailAndPassword(auth, 'admin@fmu.com', 'admin123');
  } catch (e) {
    try {
      console.log('Creating seed admin account...');
      await createUserWithEmailAndPassword(auth, 'admin@fmu.com', 'admin123');
    } catch (err) {
      console.log('Auth failed, attempting unauthenticated seeding...');
    }
  }

  console.log('🚀 Starting Merchant Seeding...');
  const merchantsRef = collection(db, 'merchants');
  
  for (const merchant of MERCHANTS) {
    try {
      await setDoc(doc(merchantsRef, merchant.id), merchant);
      console.log(`✅ Seeded: ${merchant.name}`);
    } catch (e) {
      console.error(`❌ Failed: ${merchant.name}`, e);
    }
  }
  console.log('🏁 Seeding Complete!');
  process.exit(0);
}

seed();
